general {
    hide_cursor = true
    grace = 3
}

background {
    monitor =
    color = rgba(1e1e2eff)
    blur_passes = 3
    blur_size = 8
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.25
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(cba6f7ff)
    inner_color = rgba(313244ff)
    font_color = rgba(cdd6f4ff)
    check_color = rgba(a6e3a1ff)
    fail_color = rgba(f38ba8ff)
    fade_on_empty = false
    placeholder_text = <i>Password...</i>
    hide_input = false
    position = 0, -50
    halign = center
    valign = center
    rounding = 15
}

label {
    monitor =
    text = $TIME12
    font_size = 64
    font_family = AtkynsonMono Nerd Font
    color = rgba(cdd6f4ff)
    position = 0, 100
    halign = center
    valign = center
}

label {
    monitor =
    text = Hi, $USER
    font_size = 20
    font_family = AtkynsonMono Nerd Font
    color = rgba(bac2deff)
    position = 0, 30
    halign = center
    valign = center
}
